### ISSUE TITLE
nginx websocket connection to daphne fails

### ISSUE THREAD

**Issue by luissalgadofreire** [andrewgodwin/channels#157]
Hi.

I'm trying to setup an environment where nginx serves as reverse proxy both for HTTP and Websocket connections.

Websocket connections work fine when making calls directly to daphne, which is listening on port 8000 but fail when going through nginx, which is listening on port 80 (and forwarding to daphne on port 8000).

Everything works fine in this environment except the nginx to daphne websocket connection. I'm using the following nginx configuration:

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream daphne {
    server 192.168.99.102:8000;
}

server {

    listen 80;
    charset utf-8;
    access_log  /var/log/nginx/default.access.log;
    error_log  /var/log/nginx/default.error.log;

    location /static/ {
        autoindex on;
        root /www;
    }

    location /media/ {
        autoindex on;
        #internal;
        root /www;
    }

    # websocket server path
    location /ws/ {
        proxy_pass          http://daphne;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade             $http_upgrade;
        proxy_set_header    Connection          "Upgrade";
    }

    # webserver path
    location / {
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-NginX-Proxy       true;
        proxy_pass          http://daphne;
        proxy_redirect off;
    }

}
```
And to test the connection, I'm inserting the following code in Chrome's Dev Console:
```
socket = new WebSocket("ws://192.168.99.102");
(e) {
      alert(e.data);
     }
socket.send(1);
```

This code returns: 
`WebSocket connection to 'ws://192.168.99.102/' failed: Error during WebSocket handshake: Unexpected response code: 200`

Using `ngrep 'Host: 192.168.99.102' port 80` in the nginx server yields something like:
```
interface: eth0 (172.18.0.0/255.255.0.0)
filter: (ip or ip6) and ( port 80 )
match: Host: 192.168.99.102
####
T 192.168.99.1:53021 -> 172.18.0.6:80 [AP]
  GET / HTTP/1.1..Host: 192.168.99.102..Connection: Upgrade..Pragma: no-cache..Cache-Control: no-cache..Upgrade: websocket..Origin: http://192.168.99.102..Sec-WebSocket-Version: 13..DNT: 1..User
  -Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36..Accept-Encoding: gzip, deflate, sdch..Accept-Language: en-US,en;q=0.8..C
  ookie: djdt=hide; sessionid=qbbn0qred5naamavwxjydrbxlfwwi7bf; csrftoken=0itvvLQ6dja55PAwTcedYRJ7hXowjL7V..Sec-WebSocket-Key: EYOVw+nM66JeU23DO3as+Q==..Sec-WebSocket-Extensions: permessage-defl
  ate; client_max_window_bits....
#####
```
...and using `ngrep 'Host: 192.168.99.102' port 8000` in the daphne server yields something like:
```
interface: eth0 (172.18.0.0/255.255.0.0)
filter: (ip or ip6) and ( port 8000 )
match: Host: 192.168.99.102
####
T 172.18.0.1:39906 -> 172.18.0.5:8000 [AP]
  GET / HTTP/1.0..Host: 192.168.99.102..X-Real-IP: 192.168.99.1..X-Forwarded-For: 192.168.99.1..X-NginX-Proxy: true..Connection: close..Pragma: no-cache..Cache-Control: no-cache..Origin: http://
  192.168.99.102..Sec-WebSocket-Version: 13..DNT: 1..User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36..Accept-Encoding:
  gzip, deflate, sdch..Accept-Language: en-US,en;q=0.8..Cookie: djdt=hide; sessionid=qbbn0qred5naamavwxjydrbxlfwwi7bf; csrftoken=0itvvLQ6dja55PAwTcedYRJ7hXowjL7V..Sec-WebSocket-Key: TxR8nozreG0i
  1R/4rIbFmQ==..Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits....
############
```

However, if I execute the same code on Chrome but using Daphne's port:
```
socket = new WebSocket("ws://192.168.99.102:8000");
(e) {
      alert(e.data);
`     }
socket.send(1);
```

...using `ngrep 'Host: 192.168.99.102' port 8000` in the daphne server yields something like:

```
interface: eth0 (172.18.0.0/255.255.0.0)
filter: (ip or ip6) and ( port 8000 )
match: Host: 192.168.99.102
##########
T 192.168.99.1:53005 -> 172.18.0.5:8000 [AP]
  GET / HTTP/1.1..Host: 192.168.99.102:8000..Connection: Upgrade..Pragma: no-cache..Cache-Control: no-cache..Upgrade: websocket..Origin: http://192.168.99.102..Sec-WebSocket-Version: 13..DNT: 1.
  .User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36..Accept-Encoding: gzip, deflate, sdch..Accept-Language: en-US,en;q=0
  .8..Cookie: djdt=hide; sessionid=qbbn0qred5naamavwxjydrbxlfwwi7bf; csrftoken=0itvvLQ6dja55PAwTcedYRJ7hXowjL7V..Sec-WebSocket-Key: zddCqNWKRpTuqoGDDuOkBw==..Sec-WebSocket-Extensions: permessage
  -deflate; client_max_window_bits....
###
```

In this case, all works well and the expected alert is returned in Chrome.

I'm using docker and docker-compose looks like:
```
version: '2'

services:

  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
      - memcached:memcached
    volumes:
      - ./web:/usr/src/app
      - ./web/static:/www/static
      - ./web/media:/www/media
    env_file: .env_dev
    command: daphne server.asgi:channel_layer --port 8000 --bind 0.0.0.0
    #command: /usr/local/bin/python manage.py runworker

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/log:/var/log/nginx/
    volumes_from:
      - web
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  memcached:
    restart: always
    image: memcached:latest
    ports:
      - "11211:11211"

volumes:
  redis-data: {}
  pg-data: {}
```

Am I missing something to route calls through nginx to daphne/channels?

Any help is greatly appreciated.

Regards,

Luis Freire
